name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          ./gradlew build
          cd idea-plugin
          ./gradlew buildPlugin -Dorg.gradle.project.intellij.publish.token=unknown
          cd ..
          cd idea-plugin-test
          ./gradlew build
          cd ..
